


function findSubsequence(gene: string, from: number, length: number) {
    return gene.substr(from, from + length);
}

function findSubsequenceFunc(from: number, length: number) {
    return function (gene: string) {
        return gene.substr(from, from + length);
    }
}



let gene = `atggctgttactaatgtcgct   gaacttaac  gcactcgtagagcgtgtaaaaaaagcccag
cgtgaatatgccagtttcactcaagagcaagtagacaaaatcttccgcgccgccgctctg
gctgctgcagatgctcgaatcccactcgcgaaaatggccgttgccgaatccggcatgggt
atcgtcgaagataaagtgatcaaaaaccactttgcttctgaatatatctacaacgcctat
aaagatgaaaaaacctgtggtgttctgtctgaagacgacacttttggtaccatcactatc
gctgaaccaatcggtattatttgcggtatcgttccgaccactaacccgacttcaactgct
atcttcaaatcgctgatcagtctgaagacccgtaacgccattatcttctccccgcacccg
cgtgcaaaagatgccaccaacaaagcggctgatatcgttctgcaggctgctatcgctgcc
ggtgctccgaaagatctgatcggctggatcgatcaaccttctgttgaactgtctaacgca
ctgatgcaccacccagacatcaacctgatcctcgcgactggtggtccgggcatggttaaa
gccgcatacagctccggtaaaccagctatcggtgtaggcgcgggcaacactccagttgtt
atcgatgaaactgctgatatcaaacgtgcagttgcatctgtactgatgtccaaaaccttc
gacaacggcgtaatctgtgcttctgaacagtctgttgttgttgttgactctgtttatgac
gctgtacgtgaacgttttgcaacccacggcggctatctgttgcagggtaaagagctgaaa
gctgttcaggatgttatcctgaaaaacggtgcgctgaacgcggctatcgttggtcagcca
gcctataaaattgctgaactggcaggcttctctgtaccagaaaacaccaagattctgatc
ggtgaagtgaccgttgttgatgaaagcgaaccgttcgcacatgaaaaactgtccccgact
ctggcaatgtaccgcgctaaagatttcgaagacgcggtagaaaaagcagagaaactggtt
gctatgggcggtatcggtcatacctcttgcctgtacactgaccaggataaccaaccggct
cgcgtttcttacttcggtcagaaaatgaaaacggcgcgtatcctgattaacaccccagcg
tctcagggtggtatcggtgacctgtataacttcaaactcgcaccttccctgactctgggt
tgtggttcttggggtggtaactccatctctgaaaacgttggtccgaaacacctgatcaac
aagaaaaccgttgctaagcgagctgaaaacatgttgtggcacaaacttccgaaatctatc
tacttccgccgtggctccctgccaatcgcgctggatgaagtgattactgatggccacaaa
cgtgcgctcatcgtgactgaccgcttcctgttcaacaatggttatgctgatcagatcact
tccgtactgaaagcagcaggcgttgaaactgaagtcttcttcgaagtagaagcggacccg
accctgagcatcgttcgtaaaggtgcagaactggcaaactccttcaaaccagacgtgatt
atcgcgctgggtggtggttccccgatggacgccgcgaagatcatgtgggttatgtacgaa
catccggaaactcacttcgaagagctggcgctgcgctttatggatatccgtaaacgtatc
tacaagttcccgaaaatgggcgtgaaagcgaaaatgatcgctgtcaccaccacttctggt
acaggttctgaagtcactccgtttgcggttgtaactgacgacgctactggtcagaaatat
ccgctggcagactatgcgctgactccggatatggcgattgtcgacgccaacctggttatg
gacatgccgaagtccctgtgtgctttcggtggtctggacgcagtaactcacgccatggaa
gcttatgtttctgtactggcatctgagttctctgatggtcaggctctgcaggcactgaaa
ctgctgaaagaatatctgccagcgtcctaccacgaagggtctaaaaatccggtagcgcgt
gaacgtgttcacagtgcagcgactatcgcgggtatcgcgtttgcgaacgccttcctgggt
gtatgtcactcaatggcgcacaaactgggttcccagttccatattccgcacggtctggca
aacgccctgctgatttgtaacgttattcgctacaatgcgaacgacaacccgaccaagcag
actgcattcagccagtatgaccgtccgcaggctcgccgtcgttatgctgaaattgccgac
cacttgggtctgagcgcaccgggcgaccgtactgctgctaagatcgagaaactgctggca
tggctggaaacgctgaaagctgaactgggtattccgaaatctatccgtgaagctggcgtt
caggaagcagacttcctggcgaacgtggataaactgtctgaagatgcattcgatgaccag
tgcaccggcgctaacccgcgttacccgctgatctccgagctgaaacagattctgctggat
acctactacggtcgtgattatgtagaaggtgaaactgcagcgaagaaagaagctgctccg
gctaaagctgagaaaaaagcgaaaaaatccgcttaa`;

gene = gene.replace(/\s+/ig, '');

console.log(gene);

let subsequence =  findSubsequence(gene, 50, 100);

console.log('findSubsequence:', subsequence);

