trigger:
  branches:
    include:
    - main
  paths:
    include:
    - 'types/*'

variables:
- name: project
  value: 'types'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    node azure-devops/replace.js --file=$(project)/package.json -- --Build.BuildId=$(Build.BuildId)
- task: Npm@1
  inputs:
    command: 'publish'
    customCommand: '--access public'
    workingDir: '$(project)'
    publishEndpoint: 'errisy@npm'
