trigger:
  branches:
    include:
    - main
  paths:
    include:
    - 'types/*'

variables:
- name: project
  value: 'types'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Npm@1
  inputs:
    command: 'publish'
    workingDir: '$(project)'
    publishEndpoint: 'errisy@npm'