trigger:
  branches:
    include:
    - main
  paths:
    include:
    - 'source/*'

variables:
- name: project
  value: 'source'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    node azure-devops/replace.js --file=$(project)/package.json -- --Build.BuildId=$(Build.BuildId)
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'publish --access=public'
    workingDir: '$(project)'
    publishEndpoint: 'errisy@npm'
    customRegistry: 'useNpmrc'
